/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'freed' at '19/07/20 13:02' with Gradle 2.14.1
 *
 * @author freed, @date 19/07/20 13:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
